services:
  flyrag:
    container_name: flyrag-api
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - redis
      - mysql
      - weaviate
  minio:
    container_name: flyrag-minio
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live' ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./volumes/minio-data:/data
  redis:
    container_name: flyrag-redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./volumes/redis-data:/data
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 30s
      timeout: 20s
      retries: 3
  mysql:
    container_name: flyrag-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
      - ./volumes/mysql-config:/etc/mysql/conf.d
      - ./volumes/mysql-logs:/logs
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '--password=${MYSQL_ROOT_PASSWORD}']
      interval: 30s
      timeout: 20s
      retries: 3
  weaviate:
    container_name: flyrag-weaviate
    image: semitechnologies/weaviate:latest
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY}
      AUTHENTICATION_APIKEY_USERS: 'flyrag'
      AUTHORIZATION_ENABLE_RBAC: 'true'
      AUTHORIZATION_RBAC_ROOT_USERS: 'flyrag'
    volumes:
      - ./volumes/weaviate-data:/var/lib/weaviate




